# Generated by Django 2.1.15 on 2022-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('age', models.CharField(max_length=200, verbose_name='Age')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='Department')),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
